"""Editable expansion catalog; generation logic lives in the build script."""

# stage, domain, id, product name, focus key, official product/docs URL, signals
EXPANDED_TOOL_ROWS = (
    # Analysis / software
    ("analysis", "software", "m365-copilot-researcher", "Microsoft 365 Copilot Researcher", "enterprise_research", "https://www.microsoft.com/en-us/microsoft-365-copilot", ("enterprise", "documents", "workspace", "research")),
    ("analysis", "software", "grok-deepsearch", "Grok DeepSearch", "web_research", "https://x.ai/grok", ("web", "current", "research", "citations")),
    ("analysis", "software", "you-ari", "You.com ARI", "web_research", "https://you.com/ari", ("web", "research", "report", "citations")),
    ("analysis", "software", "glean", "Glean", "enterprise_search", "https://www.glean.com/product/ai", ("enterprise", "search", "workspace", "documents")),
    ("analysis", "software", "alphasense", "AlphaSense", "market_intelligence", "https://www.alpha-sense.com/platform/", ("enterprise", "market", "documents", "research")),
    ("analysis", "software", "feedly-ai", "Feedly AI", "monitoring_research", "https://feedly.com/ai", ("monitoring", "current", "web", "discovery")),
    ("analysis", "software", "ibm-watsonx-discovery", "IBM watsonx Discovery", "document_discovery", "https://www.ibm.com/products/watson-discovery", ("enterprise", "documents", "search", "integration")),
    ("analysis", "software", "docling", "Docling", "document_conversion", "https://docling-project.github.io/docling/", ("documents", "local", "open_source", "structured")),
    ("analysis", "software", "exa", "Exa", "developer_search", "https://exa.ai/", ("api", "web", "search", "developer")),
    ("analysis", "software", "tavily", "Tavily", "developer_search", "https://docs.tavily.com/", ("api", "web", "search", "agent")),
    ("analysis", "software", "diffbot", "Diffbot", "web_extraction", "https://www.diffbot.com/products/extract/", ("api", "web", "structured", "scale")),
    ("analysis", "software", "phind", "Phind", "developer_research", "https://www.phind.com/", ("developer", "code", "web", "fast")),

    # Analysis / artificial intelligence
    ("analysis", "artificial_intelligence", "semantic-scholar", "Semantic Scholar", "literature_discovery", "https://www.semanticscholar.org/product/api", ("academic", "citations", "discovery", "api")),
    ("analysis", "artificial_intelligence", "researchrabbit", "ResearchRabbit", "literature_mapping", "https://www.researchrabbit.ai/", ("academic", "visual", "discovery", "citations")),
    ("analysis", "artificial_intelligence", "connected-papers", "Connected Papers", "literature_mapping", "https://www.connectedpapers.com/", ("academic", "visual", "citations", "discovery")),
    ("analysis", "artificial_intelligence", "litmaps", "Litmaps", "literature_mapping", "https://www.litmaps.com/", ("academic", "monitoring", "visual", "citations")),
    ("analysis", "artificial_intelligence", "scispace", "SciSpace", "paper_analysis", "https://scispace.com/", ("academic", "documents", "summary", "citations")),
    ("analysis", "artificial_intelligence", "rayyan", "Rayyan", "systematic_review", "https://www.rayyan.ai/", ("academic", "collaboration", "screening", "review")),
    ("analysis", "artificial_intelligence", "covidence", "Covidence", "systematic_review", "https://www.covidence.org/", ("academic", "collaboration", "screening", "structured")),
    ("analysis", "artificial_intelligence", "asreview", "ASReview", "systematic_review", "https://asreview.nl/", ("academic", "open_source", "local", "screening")),
    ("analysis", "artificial_intelligence", "zotero", "Zotero", "reference_management", "https://www.zotero.org/", ("academic", "open_source", "local", "citations")),
    ("analysis", "artificial_intelligence", "scholarcy", "Scholarcy", "paper_analysis", "https://www.scholarcy.com/", ("academic", "summary", "documents", "fast")),
    ("analysis", "artificial_intelligence", "iris-ai", "Iris.ai", "literature_discovery", "https://iris.ai/", ("academic", "discovery", "documents", "research")),
    ("analysis", "artificial_intelligence", "openalex", "OpenAlex", "research_graph", "https://openalex.org/", ("academic", "open", "api", "citations")),

    # Analysis / cybersecurity
    ("analysis", "cybersecurity", "recorded-future", "Recorded Future Intelligence Cloud", "threat_intelligence", "https://www.recordedfuture.com/platform", ("threat_intel", "enterprise", "current", "monitoring")),
    ("analysis", "cybersecurity", "mandiant-advantage", "Mandiant Advantage Threat Intelligence", "threat_intelligence", "https://cloud.google.com/security/products/threat-intelligence", ("threat_intel", "enterprise", "current", "investigation")),
    ("analysis", "cybersecurity", "cortex-xsiam", "Palo Alto Cortex XSIAM", "soc_analytics", "https://www.paloaltonetworks.com/cortex/cortex-xsiam", ("soc", "enterprise", "automation", "monitoring")),
    ("analysis", "cybersecurity", "microsoft-sentinel", "Microsoft Sentinel", "soc_analytics", "https://learn.microsoft.com/en-us/azure/sentinel/overview", ("soc", "enterprise", "cloud", "investigation")),
    ("analysis", "cybersecurity", "splunk-enterprise-security", "Splunk Enterprise Security", "soc_analytics", "https://www.splunk.com/en_us/products/enterprise-security.html", ("soc", "enterprise", "monitoring", "analytics")),
    ("analysis", "cybersecurity", "ibm-qradar-suite", "IBM QRadar Suite", "soc_analytics", "https://www.ibm.com/products/qradar", ("soc", "enterprise", "investigation", "integration")),
    ("analysis", "cybersecurity", "rapid7-insightidr", "Rapid7 InsightIDR", "soc_analytics", "https://www.rapid7.com/products/insightidr/", ("soc", "cloud", "monitoring", "investigation")),
    ("analysis", "cybersecurity", "darktrace", "Darktrace", "network_detection", "https://www.darktrace.com/products", ("network", "monitoring", "enterprise", "detection")),
    ("analysis", "cybersecurity", "vectra-ai", "Vectra AI Platform", "network_detection", "https://www.vectra.ai/products/platform", ("network", "monitoring", "enterprise", "detection")),
    ("analysis", "cybersecurity", "elastic-security", "Elastic Security", "soc_analytics", "https://www.elastic.co/security", ("soc", "open_source", "self_hosted", "analytics")),
    ("analysis", "cybersecurity", "sumo-logic-cloud-siem", "Sumo Logic Cloud SIEM", "soc_analytics", "https://www.sumologic.com/solutions/cloud-siem-enterprise/", ("soc", "cloud", "monitoring", "analytics")),
    ("analysis", "cybersecurity", "opencti", "OpenCTI Community Edition", "threat_intelligence", "https://github.com/OpenCTI-Platform/opencti", ("threat_intel", "self_hosted", "open_source", "investigation")),

    # Design / software
    ("design", "software", "penpot", "Penpot", "interface_design", "https://penpot.app/", ("open_source", "collaboration", "prototype", "design_system")),
    ("design", "software", "sketch", "Sketch", "interface_design", "https://www.sketch.com/", ("visual", "prototype", "design_system", "handoff")),
    ("design", "software", "axure-rp", "Axure RP", "interaction_prototyping", "https://www.axure.com/", ("prototype", "interaction", "documentation", "enterprise")),
    ("design", "software", "balsamiq", "Balsamiq", "wireframing", "https://balsamiq.com/wireframes/", ("wireframe", "fast", "collaboration", "low_fidelity")),
    ("design", "software", "miro", "Miro", "collaborative_design", "https://miro.com/", ("collaboration", "diagram", "planning", "visual")),
    ("design", "software", "lucidchart", "Lucidchart", "diagramming", "https://www.lucidchart.com/pages/", ("diagram", "collaboration", "enterprise", "integration")),
    ("design", "software", "relume", "Relume", "website_design", "https://www.relume.io/", ("web", "wireframe", "prototype", "fast")),
    ("design", "software", "webflow", "Webflow", "website_design", "https://webflow.com/", ("web", "publish", "visual", "low_code")),
    ("design", "software", "flutterflow", "FlutterFlow", "application_design", "https://www.flutterflow.io/", ("low_code", "mobile", "prototype", "publish")),
    ("design", "software", "builder-io", "Builder.io", "application_design", "https://www.builder.io/", ("visual", "web", "integration", "developer")),
    ("design", "software", "visily", "Visily", "interface_design", "https://www.visily.ai/", ("visual", "prototype", "collaboration", "fast")),
    ("design", "software", "mockflow", "MockFlow", "wireframing", "https://mockflow.com/", ("wireframe", "planning", "collaboration", "fast")),

    # Design / artificial intelligence
    ("design", "artificial_intelligence", "stable-diffusion", "Stable Diffusion", "image_generation", "https://stability.ai/stable-image", ("visual", "local", "models", "creative")),
    ("design", "artificial_intelligence", "comfyui", "ComfyUI", "node_image_workflows", "https://github.com/comfyanonymous/ComfyUI", ("open_source", "local", "workflow", "visual")),
    ("design", "artificial_intelligence", "automatic1111", "AUTOMATIC1111 Stable Diffusion WebUI", "local_image_workflows", "https://github.com/AUTOMATIC1111/stable-diffusion-webui", ("open_source", "local", "visual", "models")),
    ("design", "artificial_intelligence", "invokeai", "InvokeAI", "local_image_workflows", "https://github.com/invoke-ai/InvokeAI", ("open_source", "local", "workflow", "visual")),
    ("design", "artificial_intelligence", "leonardo-ai", "Leonardo AI", "image_generation", "https://leonardo.ai/", ("visual", "creative", "editing", "cloud")),
    ("design", "artificial_intelligence", "ideogram", "Ideogram", "image_generation", "https://ideogram.ai/", ("visual", "creative", "typography", "cloud")),
    ("design", "artificial_intelligence", "flux", "Black Forest Labs FLUX", "image_generation", "https://blackforestlabs.ai/", ("visual", "models", "creative", "api")),
    ("design", "artificial_intelligence", "runway", "Runway", "video_generation", "https://runwayml.com/", ("video", "visual", "editing", "creative")),
    ("design", "artificial_intelligence", "microsoft-designer", "Microsoft Designer", "graphic_design", "https://designer.microsoft.com/", ("visual", "templates", "editing", "fast")),
    ("design", "artificial_intelligence", "recraft", "Recraft", "graphic_design", "https://www.recraft.ai/", ("visual", "vector", "editing", "creative")),
    ("design", "artificial_intelligence", "krea", "Krea", "creative_iteration", "https://www.krea.ai/", ("visual", "iteration", "editing", "fast")),
    ("design", "artificial_intelligence", "playground-ai", "Playground AI", "image_generation", "https://playground.com/", ("visual", "editing", "creative", "cloud")),

    # Design / cybersecurity
    ("design", "cybersecurity", "microsoft-threat-modeling-tool", "Microsoft Threat Modeling Tool", "threat_modeling", "https://learn.microsoft.com/en-us/azure/security/develop/threat-modeling-tool", ("threat_model", "windows", "diagram", "local")),
    ("design", "cybersecurity", "pytm", "pytm", "threat_modeling_as_code", "https://github.com/izar/pytm", ("threat_model", "open_source", "code", "local")),
    ("design", "cybersecurity", "threagile", "Threagile", "threat_modeling_as_code", "https://github.com/Threagile/threagile", ("threat_model", "open_source", "code", "automation")),
    ("design", "cybersecurity", "cairis", "CAIRIS", "security_requirements", "https://cairis.org/", ("requirements", "open_source", "risk", "design")),
    ("design", "cybersecurity", "securicad", "securiCAD", "attack_simulation", "https://foreseeti.com/securicad/", ("attack", "simulation", "enterprise", "risk")),
    ("design", "cybersecurity", "owasp-cornucopia", "OWASP Cornucopia", "threat_workshops", "https://owasp.org/www-project-cornucopia/", ("threat_model", "open_source", "workshop", "lightweight")),
    ("design", "cybersecurity", "threatspec", "Threatspec", "threat_modeling_as_code", "https://github.com/threatspec/threatspec", ("threat_model", "open_source", "code", "documentation")),
    ("design", "cybersecurity", "deciduous", "Deciduous", "security_decision_trees", "https://github.com/kellyshortridge/deciduous", ("open_source", "diagram", "risk", "lightweight")),
    ("design", "cybersecurity", "attack-navigator", "MITRE ATT&CK Navigator", "attack_mapping", "https://github.com/mitre-attack/attack-navigator", ("open_source", "attack", "visual", "local")),
    ("design", "cybersecurity", "attack-flow", "Attack Flow", "attack_mapping", "https://center-for-threat-informed-defense.github.io/attack-flow/", ("open_source", "attack", "visual", "structured")),
    ("design", "cybersecurity", "securityrat", "SecurityRAT", "security_requirements", "https://github.com/SecurityRAT/SecurityRAT", ("open_source", "requirements", "collaboration", "governance")),
    ("design", "cybersecurity", "safe-one", "SAFE One", "quantitative_risk", "https://safe.security/product-overview/", ("risk", "enterprise", "governance", "report")),

    # Implementation / software
    ("implementation", "software", "openai-codex", "OpenAI Codex", "coding_agent", "https://developers.openai.com/codex/", ("agent", "code", "repository", "automation")),
    ("implementation", "software", "gemini-cli", "Gemini CLI", "terminal_coding", "https://github.com/google-gemini/gemini-cli", ("terminal", "open_source", "agent", "code")),
    ("implementation", "software", "amazon-q-developer", "Amazon Q Developer", "coding_assistant", "https://aws.amazon.com/q/developer/", ("ide", "enterprise", "code", "cloud")),
    ("implementation", "software", "jetbrains-ai-assistant", "JetBrains AI Assistant", "coding_assistant", "https://www.jetbrains.com/ai/", ("ide", "code", "integration", "developer")),
    ("implementation", "software", "tabnine", "Tabnine", "coding_assistant", "https://www.tabnine.com/", ("ide", "enterprise", "code", "privacy")),
    ("implementation", "software", "sourcegraph-cody", "Sourcegraph Cody", "repository_assistant", "https://sourcegraph.com/cody", ("repository", "code", "enterprise", "search")),
    ("implementation", "software", "continue", "Continue", "coding_agent", "https://github.com/continuedev/continue", ("open_source", "ide", "models", "code")),
    ("implementation", "software", "aider", "Aider", "terminal_coding", "https://github.com/Aider-AI/aider", ("open_source", "terminal", "repository", "code")),
    ("implementation", "software", "cline", "Cline", "coding_agent", "https://github.com/cline/cline", ("open_source", "ide", "agent", "code")),
    ("implementation", "software", "roo-code", "Roo Code", "coding_agent", "https://github.com/RooCodeInc/Roo-Code", ("open_source", "ide", "agent", "code")),
    ("implementation", "software", "replit-agent", "Replit Agent", "cloud_development", "https://replit.com/ai", ("cloud", "agent", "publish", "fast")),
    ("implementation", "software", "augment-code", "Augment Code", "repository_assistant", "https://www.augmentcode.com/", ("repository", "enterprise", "agent", "code")),

    # Implementation / artificial intelligence
    ("implementation", "artificial_intelligence", "transformers", "Transformers", "model_inference", "https://huggingface.co/docs/transformers/index", ("open_source", "models", "local", "code")),
    ("implementation", "artificial_intelligence", "pytorch", "PyTorch", "model_development", "https://pytorch.org/", ("open_source", "models", "local", "training")),
    ("implementation", "artificial_intelligence", "tensorflow", "TensorFlow", "model_development", "https://www.tensorflow.org/", ("open_source", "models", "training", "deployment")),
    ("implementation", "artificial_intelligence", "jax", "JAX", "accelerated_computing", "https://docs.jax.dev/", ("open_source", "models", "training", "research")),
    ("implementation", "artificial_intelligence", "vllm", "vLLM", "model_serving", "https://docs.vllm.ai/", ("open_source", "models", "serving", "scale")),
    ("implementation", "artificial_intelligence", "ollama", "Ollama", "local_model_runtime", "https://ollama.com/", ("local", "models", "runtime", "developer")),
    ("implementation", "artificial_intelligence", "llama-cpp", "llama.cpp", "local_model_runtime", "https://github.com/ggml-org/llama.cpp", ("open_source", "local", "models", "runtime")),
    ("implementation", "artificial_intelligence", "mlx", "MLX", "apple_model_development", "https://github.com/ml-explore/mlx", ("open_source", "local", "models", "apple")),
    ("implementation", "artificial_intelligence", "haystack", "Haystack", "rag_framework", "https://haystack.deepset.ai/", ("open_source", "rag", "documents", "agent")),
    ("implementation", "artificial_intelligence", "semantic-kernel", "Semantic Kernel", "agent_framework", "https://learn.microsoft.com/en-us/semantic-kernel/overview/", ("open_source", "agent", "integration", "enterprise")),
    ("implementation", "artificial_intelligence", "autogen", "AutoGen", "agent_framework", "https://github.com/microsoft/autogen", ("open_source", "agent", "multi_agent", "research")),
    ("implementation", "artificial_intelligence", "dspy", "DSPy", "programmatic_prompting", "https://dspy.ai/", ("open_source", "models", "optimization", "code")),

    # Implementation / cybersecurity
    ("implementation", "cybersecurity", "github-advanced-security", "GitHub Advanced Security", "developer_security", "https://github.com/security/advanced-security", ("repository", "sast", "enterprise", "integration")),
    ("implementation", "cybersecurity", "sonarqube", "SonarQube", "code_quality_security", "https://www.sonarsource.com/products/sonarqube/", ("sast", "self_hosted", "ci", "code")),
    ("implementation", "cybersecurity", "checkmarx-one", "Checkmarx One", "application_security", "https://checkmarx.com/product/checkmarx-one/", ("sast", "enterprise", "appsec", "integration")),
    ("implementation", "cybersecurity", "veracode-fix", "Veracode Fix", "secure_remediation", "https://www.veracode.com/products/veracode-fix/", ("fix", "enterprise", "appsec", "automation")),
    ("implementation", "cybersecurity", "codeql-cli", "CodeQL CLI", "code_scanning", "https://docs.github.com/en/code-security/codeql-cli", ("sast", "query", "repository", "local")),
    ("implementation", "cybersecurity", "bandit", "Bandit", "python_security", "https://bandit.readthedocs.io/", ("open_source", "sast", "python", "local")),
    ("implementation", "cybersecurity", "brakeman", "Brakeman", "rails_security", "https://brakemanscanner.org/", ("open_source", "sast", "ruby", "local")),
    ("implementation", "cybersecurity", "spotbugs", "SpotBugs", "java_analysis", "https://spotbugs.github.io/", ("open_source", "sast", "java", "local")),
    ("implementation", "cybersecurity", "trivy", "Trivy", "supply_chain_security", "https://trivy.dev/", ("open_source", "container", "ci", "local")),
    ("implementation", "cybersecurity", "grype", "Grype", "supply_chain_security", "https://github.com/anchore/grype", ("open_source", "container", "ci", "local")),
    ("implementation", "cybersecurity", "bearer", "Bearer", "data_security_scanning", "https://github.com/Bearer/bearer", ("open_source", "sast", "privacy", "local")),
    ("implementation", "cybersecurity", "horusec", "Horusec", "application_security", "https://github.com/ZupIT/horusec", ("open_source", "sast", "ci", "local")),

    # Testing / software
    ("testing", "software", "playwright-test", "Playwright Test", "browser_testing", "https://playwright.dev/docs/test-intro", ("open_source", "web", "e2e", "code")),
    ("testing", "software", "cypress", "Cypress", "browser_testing", "https://www.cypress.io/", ("web", "e2e", "developer", "ci")),
    ("testing", "software", "selenium", "Selenium", "browser_automation", "https://www.selenium.dev/", ("open_source", "web", "automation", "code")),
    ("testing", "software", "appium", "Appium", "mobile_testing", "https://appium.io/", ("open_source", "mobile", "automation", "e2e")),
    ("testing", "software", "browserstack-automate", "BrowserStack Automate", "device_cloud_testing", "https://www.browserstack.com/automate", ("cloud", "web", "mobile", "scale")),
    ("testing", "software", "sauce-labs", "Sauce Labs", "device_cloud_testing", "https://saucelabs.com/products/platform-for-test", ("cloud", "web", "mobile", "enterprise")),
    ("testing", "software", "lambdatest", "LambdaTest", "device_cloud_testing", "https://www.lambdatest.com/", ("cloud", "web", "mobile", "scale")),
    ("testing", "software", "katalon", "Katalon", "test_automation", "https://katalon.com/", ("low_code", "web", "api", "automation")),
    ("testing", "software", "tricentis-tosca", "Tricentis Tosca", "enterprise_testing", "https://www.tricentis.com/products/automate-continuous-testing-tosca", ("enterprise", "low_code", "automation", "governance")),
    ("testing", "software", "applitools-eyes", "Applitools Eyes", "visual_testing", "https://applitools.com/platform/eyes/", ("visual", "web", "automation", "validation")),
    ("testing", "software", "functionize", "Functionize", "ai_test_automation", "https://www.functionize.com/", ("automation", "web", "ai", "enterprise")),
    ("testing", "software", "virtuoso", "Virtuoso", "ai_test_automation", "https://www.virtuoso.qa/", ("automation", "web", "low_code", "enterprise")),

    # Testing / artificial intelligence
    ("testing", "artificial_intelligence", "wandb-weave", "Weights & Biases Weave", "llm_evaluation", "https://weave-docs.wandb.ai/", ("evaluation", "tracing", "metrics", "collaboration")),
    ("testing", "artificial_intelligence", "mlflow", "MLflow", "ml_evaluation", "https://mlflow.org/docs/latest/ml/evaluation/", ("open_source", "metrics", "models", "tracking")),
    ("testing", "artificial_intelligence", "evidently", "Evidently", "ml_monitoring", "https://www.evidentlyai.com/", ("open_source", "monitoring", "metrics", "evaluation")),
    ("testing", "artificial_intelligence", "ragas", "Ragas", "rag_evaluation", "https://docs.ragas.io/", ("open_source", "rag", "evaluation", "metrics")),
    ("testing", "artificial_intelligence", "trulens", "TruLens", "llm_evaluation", "https://www.trulens.org/", ("open_source", "evaluation", "tracing", "rag")),
    ("testing", "artificial_intelligence", "promptfoo", "promptfoo", "prompt_testing", "https://www.promptfoo.dev/", ("open_source", "evaluation", "security", "ci")),
    ("testing", "artificial_intelligence", "openai-evals", "OpenAI Evals", "model_evaluation", "https://github.com/openai/evals", ("open_source", "evaluation", "models", "code")),
    ("testing", "artificial_intelligence", "inspect-ai", "Inspect AI", "model_evaluation", "https://inspect.aisi.org.uk/", ("open_source", "evaluation", "security", "research")),
    ("testing", "artificial_intelligence", "helm", "HELM", "model_benchmarking", "https://crfm.stanford.edu/helm/latest/", ("open_source", "benchmark", "models", "research")),
    ("testing", "artificial_intelligence", "lighteval", "LightEval", "model_benchmarking", "https://github.com/huggingface/lighteval", ("open_source", "benchmark", "models", "local")),
    ("testing", "artificial_intelligence", "langfuse", "Langfuse", "llm_observability", "https://langfuse.com/docs", ("open_source", "tracing", "monitoring", "evaluation")),
    ("testing", "artificial_intelligence", "braintrust", "Braintrust", "llm_evaluation", "https://www.braintrust.dev/", ("evaluation", "metrics", "collaboration", "production")),

    # Testing / cybersecurity
    ("testing", "cybersecurity", "owasp-zap", "OWASP ZAP", "web_security_testing", "https://www.zaproxy.org/", ("open_source", "dast", "web", "local")),
    ("testing", "cybersecurity", "nuclei", "Nuclei", "template_security_scanning", "https://docs.projectdiscovery.io/tools/nuclei/overview", ("open_source", "dast", "automation", "ci")),
    ("testing", "cybersecurity", "nmap", "Nmap", "network_scanning", "https://nmap.org/", ("open_source", "network", "local", "security")),
    ("testing", "cybersecurity", "metasploit", "Metasploit Framework", "penetration_testing", "https://www.metasploit.com/", ("open_source", "security", "manual", "local")),
    ("testing", "cybersecurity", "kali-linux", "Kali Linux", "penetration_testing", "https://www.kali.org/", ("open_source", "security", "manual", "local")),
    ("testing", "cybersecurity", "sqlmap", "sqlmap", "database_security_testing", "https://sqlmap.org/", ("open_source", "dast", "database", "local")),
    ("testing", "cybersecurity", "greenbone", "Greenbone OpenVAS", "vulnerability_scanning", "https://www.greenbone.net/en/community-edition/", ("open_source", "network", "vulnerability", "self_hosted")),
    ("testing", "cybersecurity", "nessus", "Nessus", "vulnerability_scanning", "https://www.tenable.com/products/nessus", ("vulnerability", "network", "enterprise", "local")),
    ("testing", "cybersecurity", "acunetix", "Acunetix", "web_security_testing", "https://www.acunetix.com/", ("dast", "web", "enterprise", "automation")),
    ("testing", "cybersecurity", "pentera", "Pentera", "automated_security_validation", "https://pentera.io/", ("security", "automation", "enterprise", "validation")),
    ("testing", "cybersecurity", "detectify", "Detectify", "web_security_testing", "https://detectify.com/", ("dast", "web", "cloud", "monitoring")),
    ("testing", "cybersecurity", "probely", "Probely", "web_api_security_testing", "https://probely.com/", ("dast", "web", "api", "automation")),
)


FOCUS_AR = {
    "accelerated_computing": "الحوسبة المسرّعة",
    "agent_framework": "بناء الوكلاء",
    "ai_test_automation": "أتمتة الاختبارات بالذكاء الاصطناعي",
    "apple_model_development": "تطوير النماذج على أجهزة آبل",
    "application_design": "تصميم التطبيقات",
    "application_security": "أمن التطبيقات",
    "attack_mapping": "رسم خرائط الهجمات",
    "attack_simulation": "محاكاة الهجمات",
    "automated_security_validation": "التحقق الأمني المؤتمت",
    "browser_automation": "أتمتة المتصفح",
    "browser_testing": "اختبار المتصفحات",
    "cloud_development": "التطوير السحابي",
    "code_quality_security": "جودة الشيفرة وأمنها",
    "code_scanning": "فحص الشيفرة",
    "coding_agent": "وكلاء البرمجة",
    "coding_assistant": "المساعدة في البرمجة",
    "collaborative_design": "التصميم التعاوني",
    "creative_iteration": "التنقيح الإبداعي",
    "data_security_scanning": "فحص أمن البيانات",
    "database_security_testing": "اختبار أمن قواعد البيانات",
    "developer_research": "البحث للمطورين",
    "developer_search": "البحث البرمجي",
    "developer_security": "الأمن للمطورين",
    "device_cloud_testing": "الاختبار على أجهزة سحابية",
    "diagramming": "رسم المخططات",
    "document_conversion": "تحويل المستندات إلى محتوى منظم",
    "document_discovery": "استكشاف المستندات",
    "enterprise_research": "البحث المؤسسي",
    "enterprise_search": "البحث في محتوى المؤسسة",
    "enterprise_testing": "الاختبارات المؤسسية",
    "graphic_design": "التصميم الجرافيكي",
    "image_generation": "توليد الصور",
    "interaction_prototyping": "نمذجة التفاعلات الأولية",
    "interface_design": "تصميم الواجهات",
    "java_analysis": "تحليل شيفرة جافا",
    "literature_discovery": "اكتشاف الأدبيات العلمية",
    "literature_mapping": "رسم خرائط الأدبيات العلمية",
    "llm_evaluation": "تقييم النماذج اللغوية الكبيرة",
    "llm_observability": "مراقبة تطبيقات النماذج اللغوية الكبيرة",
    "local_image_workflows": "معالجة الصور محلياً",
    "local_model_runtime": "تشغيل النماذج محلياً",
    "market_intelligence": "استخبارات السوق",
    "ml_evaluation": "تقييم تعلم الآلة",
    "ml_monitoring": "مراقبة تعلم الآلة",
    "mobile_testing": "اختبار تطبيقات الجوال",
    "model_benchmarking": "المقارنة المعيارية للنماذج",
    "model_development": "تطوير النماذج",
    "model_evaluation": "تقييم النماذج",
    "model_inference": "الاستدلال بالنماذج",
    "model_serving": "تقديم النماذج كخدمات",
    "monitoring_research": "رصد المصادر البحثية",
    "network_detection": "كشف تهديدات الشبكات",
    "network_scanning": "فحص الشبكات",
    "node_image_workflows": "معالجة الصور بمخططات العقد",
    "paper_analysis": "تحليل الأوراق العلمية",
    "penetration_testing": "اختبار الاختراق",
    "programmatic_prompting": "إدارة التوجيهات برمجياً",
    "prompt_testing": "اختبار التوجيهات",
    "python_security": "أمن شيفرة بايثون",
    "quantitative_risk": "التحليل الكمي للمخاطر",
    "rag_evaluation": "تقييم التوليد المعزز بالاسترجاع",
    "rag_framework": "بناء التوليد المعزز بالاسترجاع",
    "rails_security": "أمن تطبيقات ريلز",
    "reference_management": "إدارة المراجع",
    "repository_assistant": "المساعدة في مستودعات الشيفرة",
    "research_graph": "خرائط العلاقات البحثية",
    "secure_remediation": "معالجة الثغرات الأمنية",
    "security_decision_trees": "أشجار القرارات الأمنية",
    "security_requirements": "المتطلبات الأمنية",
    "soc_analytics": "تحليلات مركز العمليات الأمنية",
    "supply_chain_security": "أمن سلسلة التوريد البرمجية",
    "systematic_review": "المراجعة المنهجية",
    "template_security_scanning": "الفحص الأمني بالقوالب",
    "terminal_coding": "البرمجة من الطرفية",
    "test_automation": "أتمتة الاختبارات",
    "threat_intelligence": "استخبارات التهديدات",
    "threat_modeling": "نمذجة التهديدات",
    "threat_modeling_as_code": "نمذجة التهديدات كشيفرة",
    "threat_workshops": "ورش تحليل التهديدات",
    "video_generation": "توليد الفيديو",
    "visual_testing": "الاختبار البصري",
    "vulnerability_scanning": "فحص الثغرات",
    "web_api_security_testing": "اختبار أمن الويب وواجهات البرمجة",
    "web_extraction": "استخراج المحتوى من الويب",
    "web_research": "البحث عبر الويب",
    "web_security_testing": "اختبار أمن الويب",
    "website_design": "تصميم المواقع",
    "wireframing": "تصميم المخططات الهيكلية للواجهات",
}

# Task-specific caveats for reviewed records; capability evidence remains in profiles.
TOOL_LIMITATIONS = {
    "docling": (
        "Review extracted layout and tables; air-gapped conversion needs preloaded models and dependencies, and model licenses are separate from the MIT code license.",
        "راجع التخطيط والجداول المستخرجة؛ يتطلب التحويل دون شبكة تجهيز النماذج والتبعيات مسبقاً، وتراخيص النماذج منفصلة عن ترخيص الشيفرة MIT.",
    ),
    "opencti": (
        "Community Edition requires maintaining its deployment and dependencies; external feeds have separate access terms, and Enterprise Edition features need their own license.",
        "تتطلب نسخة المجتمع صيانة النشر والتبعيات؛ وللمصادر الخارجية شروط وصول منفصلة، وتحتاج ميزات النسخة المؤسسية ترخيصها الخاص.",
    ),
    "safe-one": (
        "Validate risk-scenario assumptions and confirm licensed modules and data integrations with the vendor before relying on financial risk estimates.",
        "تحقق من افتراضات سيناريو المخاطر والوحدات المرخصة وتكامل البيانات مع المورد قبل الاعتماد على تقديرات المخاطر المالية.",
    ),
    "mandiant-advantage": (
        "Confirm the specific Mandiant Advantage entitlement and its overlap with Google Threat Intelligence before selecting or comparing subscriptions.",
        "تحقق من صلاحيات اشتراك مانديانت أدفانتج وتداخله مع استخبارات تهديدات غوغل قبل اختيار الاشتراكات أو مقارنتها.",
    ),
}

FOCUS = {
    key: {
        "en": key.replace("_", " "),
        "ar": FOCUS_AR[key],
    }
    for key in {row[4] for row in EXPANDED_TOOL_ROWS}
}


# Forty-two distinct decision axes extend each stage's fourteen tailored questions.
# dimension, English label, Arabic label, flexible/balanced/strict signals
EXPANSION_AXES = (
    ("connectivity", "connectivity", "الاتصال بالشبكة", ("cloud", "web"), ("integration", "hybrid"), ("local", "offline")),
    ("preparation", "advance preparation", "التجهيز المسبق", ("fast", "managed"), ("workflow", "documentation"), ("local", "portable")),
    ("data_sensitivity", "data sensitivity", "حساسية البيانات", ("cloud", "collaboration"), ("governance", "privacy"), ("local", "security")),
    ("data_residency", "data residency", "موقع حفظ البيانات", ("cloud", "managed"), ("enterprise", "governance"), ("self_hosted", "local")),
    ("budget", "budget", "الميزانية", ("enterprise", "managed"), ("commercial", "integration"), ("free", "open_source")),
    ("licensing", "licensing", "الترخيص", ("commercial", "managed"), ("mixed", "enterprise"), ("open_source", "community")),
    ("operating_system", "operating-system support", "دعم نظام التشغيل", ("web", "cloud"), ("integration", "developer"), ("local", "portable")),
    ("hardware", "hardware", "العتاد", ("cloud", "managed"), ("balanced", "deployment"), ("local", "models")),
    ("memory", "memory usage", "استهلاك الذاكرة", ("scale", "enterprise"), ("balanced", "runtime"), ("lightweight", "local")),
    ("storage", "storage", "التخزين", ("cloud", "documents"), ("structured", "integration"), ("local", "lightweight")),
    ("skill_level", "operator skill", "خبرة المشغّل", ("expert", "code"), ("developer", "documentation"), ("low_code", "templates")),
    ("setup_effort", "setup effort", "جهد الإعداد", ("control", "self_hosted"), ("workflow", "developer"), ("fast", "managed")),
    ("maintenance", "maintenance", "الصيانة", ("self_hosted", "control"), ("integration", "workflow"), ("managed", "cloud")),
    ("deployment", "deployment", "النشر", ("cloud", "managed"), ("hybrid", "integration"), ("local", "self_hosted")),
    ("collaboration", "collaboration", "التعاون", ("solo", "local"), ("collaboration", "repository"), ("enterprise", "workspace")),
    ("governance", "governance", "الحوكمة", ("fast", "exploration"), ("validation", "documentation"), ("governance", "enterprise")),
    ("auditability", "auditability", "قابلية التدقيق", ("fast", "summary"), ("tracing", "report"), ("governance", "evidence")),
    ("explainability", "explainability", "قابلية التفسير", ("automation", "fast"), ("rationale", "validation"), ("evidence", "control")),
    ("reproducibility", "reproducibility", "قابلية إعادة الإنتاج", ("creative", "exploration"), ("versioning", "workflow"), ("local", "code")),
    ("integration", "integration depth", "عمق التكامل", ("standalone", "lightweight"), ("api", "integration"), ("enterprise", "workspace")),
    ("automation", "automation", "الأتمتة", ("manual", "expert"), ("assist", "developer"), ("automation", "agent")),
    ("scale", "scale", "الحجم", ("focused", "lightweight"), ("application", "integration"), ("scale", "enterprise")),
    ("latency", "latency", "زمن الاستجابة", ("deep", "quality"), ("balanced", "validation"), ("fast", "runtime")),
    ("throughput", "throughput", "معدل المعالجة", ("focused", "manual"), ("automation", "pipeline"), ("scale", "serving")),
    ("availability", "availability", "التوافر", ("local", "manual"), ("hybrid", "monitoring"), ("cloud", "enterprise")),
    ("portability", "portability", "قابلية النقل", ("platform", "managed"), ("export", "integration"), ("portable", "open_source")),
    ("interoperability", "interoperability", "التشغيل البيني", ("standalone", "focused"), ("api", "structured"), ("integration", "enterprise")),
    ("customization", "customization", "التخصيص", ("templates", "managed"), ("configuration", "workflow"), ("open_source", "code")),
    ("extensibility", "extensibility", "قابلية التوسعة", ("focused", "managed"), ("api", "plugins"), ("open_source", "developer")),
    ("vendor_lock_in", "vendor independence", "الاستقلال عن المورّد", ("workspace", "managed"), ("export", "standards"), ("open_source", "self_hosted")),
    ("support", "support", "الدعم", ("community", "open_source"), ("documentation", "developer"), ("enterprise", "managed")),
    ("community", "community ecosystem", "منظومة المجتمع", ("specialist", "focused"), ("developer", "integration"), ("community", "open_source")),
    ("maturity", "product maturity", "نضج المنتج", ("emerging", "exploration"), ("validation", "developer"), ("enterprise", "governance")),
    ("update_cadence", "update cadence", "وتيرة التحديث", ("stable", "governance"), ("balanced", "versioning"), ("current", "fast")),
    ("compliance", "compliance", "الامتثال", ("exploration", "manual"), ("documentation", "validation"), ("compliance", "enterprise")),
    ("access_control", "access control", "التحكم بالوصول", ("solo", "local"), ("team", "workspace"), ("enterprise", "governance")),
    ("logging", "logging", "التسجيل", ("result", "lightweight"), ("tracing", "developer"), ("monitoring", "audit")),
    ("versioning", "version control", "التحكم بالإصدارات", ("manual", "focused"), ("repository", "workflow"), ("governance", "audit")),
    ("export", "export formats", "صيغ التصدير", ("native", "managed"), ("documents", "structured"), ("open", "portable")),
    ("recovery", "recovery", "الاستعادة", ("manual", "local"), ("versioning", "workflow"), ("enterprise", "availability")),
    ("lifecycle", "lifecycle management", "إدارة دورة الحياة", ("focused", "prototype"), ("workflow", "monitoring"), ("governance", "enterprise")),
    ("human_review", "human review", "المراجعة البشرية", ("automation", "fast"), ("validation", "collaboration"), ("expert", "governance")),
)
